default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: festifind.development

test:
  <<: *default
  database: festifind.test

production:
  <<: *default
  database: festifind.production

