tdefault: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: festifind_development

test:
  <<: *default
  database: festifind_test

production:
  <<: *default
  database: festifind
